"""Fix database schema

Revision ID: 5cb926a06fbf
Revises: 98878296b947
Create Date: 2025-08-14 23:21:05.084006

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cb926a06fbf'
down_revision: Union[str, None] = '98878296b947'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'attendance', 'student', ['student_id'], ['id'])
    op.create_foreign_key(None, 'journal', 'student', ['student_id'], ['id'])
    op.alter_column('student', 'syllabus',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('student', 'focus_subjects',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('student', 'subject',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('student', 'remarks',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key(None, 'student', 'tutor', ['tutor_id'], ['id'])
    op.create_foreign_key(None, 'testrecord', 'student', ['student_id'], ['id'])
    op.create_foreign_key(None, 'tutor', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tutor', type_='foreignkey')
    op.drop_constraint(None, 'testrecord', type_='foreignkey')
    op.drop_constraint(None, 'student', type_='foreignkey')
    op.alter_column('student', 'remarks',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('student', 'subject',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('student', 'focus_subjects',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('student', 'syllabus',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'journal', type_='foreignkey')
    op.drop_constraint(None, 'attendance', type_='foreignkey')
    # ### end Alembic commands ###
