"""Fix database schema

Revision ID: 98878296b947
Revises: 
Create Date: 2025-08-14 23:12:15.744324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98878296b947'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    def upgrade() -> None:
        # Use op.batch_alter_table to enable batch mode
        with op.batch_alter_table('student', schema=None) as batch_op:
            # This will now correctly add the foreign key to the 'student' table
            batch_op.alter_column('tutor_id',
                                  existing_type=sa.INTEGER(),
                                  nullable=False)
            batch_op.create_foreign_key(None, 'tutor', ['tutor_id'], ['id'])

    def downgrade() -> None:
        # In the downgrade, you would do the opposite
        with op.batch_alter_table('student', schema=None) as batch_op:
            batch_op.drop_constraint(None, type_='foreignkey')
            batch_op.alter_column('tutor_id',
                                  existing_type=sa.INTEGER(),
                                  nullable=True)
    # ### end Alembic commands ###
